import { Inter } from "next/font/google";
import "./globals.css";
import ColorModeProvider from "@app/provider/darkMode";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ColorModeProvider>
        <Box
          component="body"
          sx={{ backgroundColor: "primary.main" }}
          className={inter.className}
        >
          {children}
        </Box>
      </ColorModeProvider>
    </html>
  );
}
