name: Build and Deploy Next.js App

on:
  push:
    branches:
      - main  # Atau branch yang kamu gunakan untuk produksi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.13.1'  # Pilih versi Node.js yang sesuai dengan projectmu

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: rakhazufar.com
        username: rakhazu
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        source: "out/*"  # Atau direktori build output yang lain sesuai konfigurasi Next.js
        target: "/home/rakhazu/public_html/text"
